// Generated by scripts/sync-entity-icons.mjs; do not edit by hand.
// Refresh with: npm run sync-icons
// Source: tirante-dev/blob-list generated_at 2026-08-09T05:08:26.194Z

export interface EntityIcon {
  /** Bundled icon path under public/. */
  src: string;
  /** CAIP-2 ref of the entity's settlement chain, e.g. eip155-1. */
  settlement: string;
  /**
   * Artwork vanishes against the dark page background but reads once a
   * light disc is put behind it. Measured at sync time by
   * scripts/iconLegibility.mjs; omitted when false.
   */
  needsLightBackdrop?: boolean;
}

/** Lowercased blob-list entity name to bundled icon. */
export const ENTITY_ICONS: Record<string, EntityIcon> = {
  'abstract': { src: '/images/entities/abstract.svg', settlement: 'eip155-1' },
  'adi chain': { src: '/images/entities/adi-chain.svg', settlement: 'eip155-1', needsLightBackdrop: true },
  'arbitrum one': { src: '/images/entities/arbitrum.svg', settlement: 'eip155-1' },
  'arbitrum sepolia': { src: '/images/entities/arbitrum-sepolia.svg', settlement: 'eip155-11155111' },
  'base': { src: '/images/entities/base.png', settlement: 'eip155-1' },
  'base sepolia testnet': { src: '/images/entities/base-sepolia.png', settlement: 'eip155-11155111' },
  'blast': { src: '/images/entities/blast.jpg', settlement: 'eip155-1' },
  'hemi': { src: '/images/entities/hemi.png', settlement: 'eip155-1' },
  'ink': { src: '/images/entities/ink.svg', settlement: 'eip155-1' },
  'katana': { src: '/images/entities/katana.png', settlement: 'eip155-1' },
  'lighter': { src: '/images/entities/lighter.svg', settlement: 'eip155-1' },
  'linea': { src: '/images/entities/linea.svg', settlement: 'eip155-1', needsLightBackdrop: true },
  'linea sepolia': { src: '/images/entities/linea-sepolia.svg', settlement: 'eip155-11155111', needsLightBackdrop: true },
  'metal l2': { src: '/images/entities/metal.svg', settlement: 'eip155-1' },
  'mode': { src: '/images/entities/mode.png', settlement: 'eip155-1' },
  'mode testnet': { src: '/images/entities/mode-sepolia.png', settlement: 'eip155-11155111' },
  'op mainnet': { src: '/images/entities/optimism.svg', settlement: 'eip155-1' },
  'op sepolia testnet': { src: '/images/entities/op-sepolia.svg', settlement: 'eip155-11155111' },
  'paradex': { src: '/images/entities/paradex.svg', settlement: 'eip155-1' },
  'robinhood chain': { src: '/images/entities/robinhood-chain.svg', settlement: 'eip155-1' },
  'robinhood chain testnet': { src: '/images/entities/robinhood-chain-testnet.svg', settlement: 'eip155-11155111' },
  'scroll': { src: '/images/entities/scroll.svg', settlement: 'eip155-1' },
  'shape': { src: '/images/entities/shape.png', settlement: 'eip155-1' },
  'soneium': { src: '/images/entities/soneium.svg', settlement: 'eip155-1' },
  'starknet': { src: '/images/entities/starknet.svg', settlement: 'eip155-1' },
  'starknet sepolia': { src: '/images/entities/starknet-sepolia.svg', settlement: 'eip155-11155111' },
  'taiko': { src: '/images/entities/taiko.png', settlement: 'eip155-1' },
  'unichain': { src: '/images/entities/unichain.png', settlement: 'eip155-1' },
  'world chain': { src: '/images/entities/world-chain.svg', settlement: 'eip155-1' },
  'x layer': { src: '/images/entities/xlayer.png', settlement: 'eip155-1' },
  'zksync era': { src: '/images/entities/zksync-era.svg', settlement: 'eip155-1' },
  'zora': { src: '/images/entities/zora.png', settlement: 'eip155-1' },
  'zora sepolia testnet': { src: '/images/entities/zora-sepolia.png', settlement: 'eip155-11155111' },
};
